name: deploy

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install
      - run: npm ci
      - run: npm test
        env:
          AD_ACCOUNT_ID: ${{secrets.AD_ACCOUNT_ID}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          DB_URL: ${{secrets.DB_URL}}

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
